# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.18.1"

gem "sinatra", "~> 2.1"

gem "libui", "~> 0.0.8"
